<?php

namespace App\Domains\Auth\Notifications\Frontend;

use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use App\Models\Invoice;
use App\Services\InvoiceService;

/**
 * Class InvoiceEmail.
 */
class InvoiceEmail extends Notification
{
    /**
     * @var InvoiceService
     */
    protected $invoiceService;

    /**
     * Create a new invoice email instance
     *
     * @param  InvoiceService  $invoiceService
     * @param  Invoice  $invoice
     * @param  array $data
     *
     * @return void
     */
    public function __construct(InvoiceService $invoiceService, Invoice $invoice, $data)
    {
        $this->invoiceService = $invoiceService;
        $this->invoice = $invoice;
        $this->locale = $data['locale'];
        $this->reply_email = $data['from'];
        $this->name = $data['name'];
    }

    /**
     * Get the notification's channels.
     *
     * @param  mixed  $notifiable
     * @return array|string
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Build the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $pdf = $this->invoiceService->generateInvoice($this->invoice->toArray(), $this->locale)->download();
        return (new MailMessage)
            ->from($this->reply_email, $this->name)
            ->replyTo($this->reply_email, $this->name)
            ->subject(__('New invoice generated by') . ' ' . $this->name)
            ->line(__('A new invoice was generated for you by') . ' ' . $this->name . ' via billtime.io')
            ->line(__('You can find the invoice attached to this email.'))
            ->line(__('For further questions, please reply to the following email: ') . $this->reply_email)
            ->attachData($pdf, "invoice_" . $this->invoice->number . "_" . $this->locale . ".pdf", [
                'mime' => 'application/pdf',
            ]);
    }
}
